# Building Node based application even for native
language: node_js
node_js: "10.5"
sudo: required

install:
  - pip install six
  - echo no | npm ci

# Setting up the build matrix: web, iOS, Android
matrix:
  include:
    # Running lint
    - stage: "Lint and unittest"
      cache:
        - directories:
            - $HOME/.npm
      addons:
        chrome: stable
      script: 
        - npm run lint
        - npm run ci-test
        - npm run coverage-report

    # Running iOS build
    - stage: "Build"
      os: osx
      osx_image: xcode9.4
      cache:
        - directories:
            - $HOME/.npm
        - cocoapods
      script:
        - npm run dist:ios

    # Running Android build
    - os: linux
      language: android
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        - directories:
            - $HOME/.gradle/caches/
            - $HOME/.gradle/wrapper/
            - $HOME/.android/build-cache
            - $HOME/.npm
      android:
        components:
          - build-tools-28.0.3
          - platform-tools
          - tools
          - android-28
          - extra-andoird-m2repository
      before_install: nvm install 10.5
      script:
        - npm run dist:android

    # Running web build
    - os: linux
      cache:
        - directories:
            - $HOME/.npm
      script:
        - npm run dist
      before_deploy:
        - echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > ~/.npmrc
        - /.travis/install-kube-tools.sh
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./.travis/publish.js
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+

    # Release if on master and not PR
    - stage: "Release new version from master"
      if: branch = master AND type != pull_request AND commit_message !~ /Bumping version to/
      cache:
        - directories:
            - $HOME/.npm
      script: 
        - ./.travis/version_bump.sh
