name: 'Setup Kirby environment'
description: 'Will checkout the repository, install node, install npm dependencies either from a cache or as a clean install'
inputs: 
  node-version: # Composite steps does not support env - added node version as input instead for DRYness
      description: 'Node version to be used for setup'
      required: true 
      default: '10.16'
runs: 
  using: "composite"
  steps: 
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - name: Fetch Node Modules Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: | 
          **/node_modules
        key: node-modules-${{ runner.os }}-${{ inputs.node-version }}-${{hashFiles('**/package.json')}}-${{hashFiles('**/package-lock.json')}}
    - name: Clean Install NPM Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Run Postinstall Script
      if: steps.cache.outputs.cache-hit == 'true'
      run: npm run postinstall 

