# This is a basic workflow to help you get started with Actions

name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate file
        run: date > time.txt

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Git test"
          git config user.email "<>"
      - name: commit and push
        run: |
          # Stage the file, commit and push
          git add time.txt
          git commit -m "new date commit"
          git push 

